version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: "${MYSQL_HOST}"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - 3306:3306
    networks:
      - bicity

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - bicity

  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      MYSQL_NAME: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: 3306
    networks:
      - bicity

networks:
  bicity: