version: '3.1'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.28-debian
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_DATABASE: db
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080